# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'objeto.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Objeto(object):
    def setupUi(self, Objeto):
        Objeto.setObjectName("Objeto")
        Objeto.resize(1077, 167)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Objeto)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblImage = QtWidgets.QLabel(Objeto)
        self.lblImage.setObjectName("lblImage")
        self.horizontalLayout.addWidget(self.lblImage)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.objetoLabel = QtWidgets.QLabel(Objeto)
        self.objetoLabel.setObjectName("objetoLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.objetoLabel)
        self.led_objeto = QtWidgets.QLineEdit(Objeto)
        self.led_objeto.setObjectName("led_objeto")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.led_objeto)
        self.legendaLabel = QtWidgets.QLabel(Objeto)
        self.legendaLabel.setObjectName("legendaLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.legendaLabel)
        self.led_legenda = QtWidgets.QLineEdit(Objeto)
        self.led_legenda.setObjectName("led_legenda")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.led_legenda)
        self.proprietRioLabel = QtWidgets.QLabel(Objeto)
        self.proprietRioLabel.setObjectName("proprietRioLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.proprietRioLabel)
        self.led_proprietario = QtWidgets.QLineEdit(Objeto)
        self.led_proprietario.setObjectName("led_proprietario")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.led_proprietario)
        self.horizontalLayout.addLayout(self.formLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)

        self.retranslateUi(Objeto)
        QtCore.QMetaObject.connectSlotsByName(Objeto)

    def retranslateUi(self, Objeto):
        _translate = QtCore.QCoreApplication.translate
        Objeto.setWindowTitle(_translate("Objeto", "Form"))
        self.lblImage.setText(_translate("Objeto", "<html><head/><body><p><br/></p></body></html>"))
        self.objetoLabel.setText(_translate("Objeto", "Objeto"))
        self.legendaLabel.setText(_translate("Objeto", "Legenda"))
        self.proprietRioLabel.setText(_translate("Objeto", "Proprietário"))
