output_folder: C:\temp
server_name: batman
shared_user: sinf
servers:
  batman:
    ip: "10.129.3.128"
    port: 8002
  superman:
    ip: "10.129.3.132"
    port: 8002
  mulher_maravilha:
    ip: "10.129.3.120"
    port: 8002
