# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 487)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(20, 260, 121, 16))
        self.label.setObjectName("label")
        self.cbxPrinter = QtWidgets.QComboBox(MainWindow)
        self.cbxPrinter.setGeometry(QtCore.QRect(140, 260, 251, 22))
        self.cbxPrinter.setObjectName("cbxPrinter")
        self.cbxPrinterDuplex = QtWidgets.QComboBox(MainWindow)
        self.cbxPrinterDuplex.setGeometry(QtCore.QRect(140, 290, 251, 22))
        self.cbxPrinterDuplex.setObjectName("cbxPrinterDuplex")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(40, 290, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(70, 320, 91, 16))
        self.label_3.setObjectName("label_3")
        self.spbCover = QtWidgets.QSpinBox(MainWindow)
        self.spbCover.setGeometry(QtCore.QRect(140, 320, 71, 22))
        self.spbCover.setProperty("value", 1)
        self.spbCover.setObjectName("spbCover")
        self.chkCapa = QtWidgets.QCheckBox(MainWindow)
        self.chkCapa.setGeometry(QtCore.QRect(220, 320, 71, 18))
        self.chkCapa.setChecked(True)
        self.chkCapa.setObjectName("chkCapa")
        self.chkLaudo = QtWidgets.QCheckBox(MainWindow)
        self.chkLaudo.setGeometry(QtCore.QRect(220, 350, 71, 18))
        self.chkLaudo.setObjectName("chkLaudo")
        self.spbLaudo = QtWidgets.QSpinBox(MainWindow)
        self.spbLaudo.setGeometry(QtCore.QRect(140, 350, 71, 22))
        self.spbLaudo.setProperty("value", 2)
        self.spbLaudo.setObjectName("spbLaudo")
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(70, 350, 91, 16))
        self.label_4.setObjectName("label_4")
        self.chkMidia = QtWidgets.QCheckBox(MainWindow)
        self.chkMidia.setGeometry(QtCore.QRect(220, 380, 71, 18))
        self.chkMidia.setObjectName("chkMidia")
        self.spbMidia = QtWidgets.QSpinBox(MainWindow)
        self.spbMidia.setGeometry(QtCore.QRect(140, 380, 71, 22))
        self.spbMidia.setObjectName("spbMidia")
        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setGeometry(QtCore.QRect(70, 380, 91, 16))
        self.label_5.setObjectName("label_5")
        self.btnPrint = QtWidgets.QPushButton(MainWindow)
        self.btnPrint.setGeometry(QtCore.QRect(10, 430, 431, 41))
        self.btnPrint.setObjectName("btnPrint")
        self.btnConfigPrinters = QtWidgets.QToolButton(MainWindow)
        self.btnConfigPrinters.setGeometry(QtCore.QRect(400, 260, 41, 51))
        self.btnConfigPrinters.setText("")
        self.btnConfigPrinters.setObjectName("btnConfigPrinters")
        self.chkSavePdf = QtWidgets.QCheckBox(MainWindow)
        self.chkSavePdf.setGeometry(QtCore.QRect(290, 350, 71, 18))
        self.chkSavePdf.setChecked(True)
        self.chkSavePdf.setObjectName("chkSavePdf")
        self.textEdit = QtWidgets.QTextEdit(MainWindow)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 421, 201))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Imprimir laudo"))
        self.label.setText(_translate("MainWindow", "Impressora face única"))
        self.label_2.setText(_translate("MainWindow", "Impressora duplex"))
        self.label_3.setText(_translate("MainWindow", "Copias capa"))
        self.chkCapa.setText(_translate("MainWindow", "Duplex"))
        self.chkLaudo.setText(_translate("MainWindow", "Duplex"))
        self.label_4.setText(_translate("MainWindow", "Copias laudo"))
        self.chkMidia.setText(_translate("MainWindow", "Duplex"))
        self.label_5.setText(_translate("MainWindow", "Copias midia"))
        self.btnPrint.setText(_translate("MainWindow", "Imprimir"))
        self.btnConfigPrinters.setToolTip(_translate("MainWindow", "Abrir impressoras no painel de controle"))
        self.chkSavePdf.setText(_translate("MainWindow", "Salvar PDF"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">App em versão beta, reporte os bugs encontrados para melhoramento</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">1- Tenha o Microsoft Word instalado em sua máquina</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">2- Instale a impressora da SINF duas vezes e configure as preferências de uma para impressão em face única e a outra para impressão em face dupla</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">3- Feche os documentos que estão abertos no Word</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">4- Clique em Imprimir</span></p></body></html>"))
