# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editar_objeto.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditarObjeto(object):
    def setupUi(self, EditarObjeto):
        EditarObjeto.setObjectName("EditarObjeto")
        EditarObjeto.resize(486, 116)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditarObjeto)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nomeLabel = QtWidgets.QLabel(EditarObjeto)
        self.nomeLabel.setObjectName("nomeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nomeLabel)
        self.led_nome = QtWidgets.QLineEdit(EditarObjeto)
        self.led_nome.setObjectName("led_nome")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.led_nome)
        self.tipoLabel = QtWidgets.QLabel(EditarObjeto)
        self.tipoLabel.setObjectName("tipoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tipoLabel)
        self.cbx_tipo = QtWidgets.QComboBox(EditarObjeto)
        self.cbx_tipo.setEditable(True)
        self.cbx_tipo.setObjectName("cbx_tipo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbx_tipo)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditarObjeto)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EditarObjeto)
        self.buttonBox.accepted.connect(EditarObjeto.accept)
        self.buttonBox.rejected.connect(EditarObjeto.reject)
        QtCore.QMetaObject.connectSlotsByName(EditarObjeto)

    def retranslateUi(self, EditarObjeto):
        _translate = QtCore.QCoreApplication.translate
        EditarObjeto.setWindowTitle(_translate("EditarObjeto", "Novo objeto"))
        self.nomeLabel.setText(_translate("EditarObjeto", "Nome"))
        self.tipoLabel.setText(_translate("EditarObjeto", "Tipo"))
