# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 404)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icones/pluguin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnInserirFigurasLegenda = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInserirFigurasLegenda.sizePolicy().hasHeightForWidth())
        self.btnInserirFigurasLegenda.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icones/figura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInserirFigurasLegenda.setIcon(icon1)
        self.btnInserirFigurasLegenda.setIconSize(QtCore.QSize(25, 25))
        self.btnInserirFigurasLegenda.setObjectName("btnInserirFigurasLegenda")
        self.gridLayout.addWidget(self.btnInserirFigurasLegenda, 5, 1, 1, 1)
        self.btnInserirFotos = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInserirFotos.sizePolicy().hasHeightForWidth())
        self.btnInserirFotos.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icones/imagens.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInserirFotos.setIcon(icon2)
        self.btnInserirFotos.setIconSize(QtCore.QSize(25, 25))
        self.btnInserirFotos.setObjectName("btnInserirFotos")
        self.gridLayout.addWidget(self.btnInserirFotos, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSubstituirTudo = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSubstituirTudo.sizePolicy().hasHeightForWidth())
        self.btnSubstituirTudo.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icones/replaceall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSubstituirTudo.setIcon(icon3)
        self.btnSubstituirTudo.setIconSize(QtCore.QSize(25, 25))
        self.btnSubstituirTudo.setObjectName("btnSubstituirTudo")
        self.horizontalLayout_2.addWidget(self.btnSubstituirTudo)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.btnSubstituirFotos = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSubstituirFotos.sizePolicy().hasHeightForWidth())
        self.btnSubstituirFotos.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icones/foto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSubstituirFotos.setIcon(icon4)
        self.btnSubstituirFotos.setIconSize(QtCore.QSize(25, 25))
        self.btnSubstituirFotos.setObjectName("btnSubstituirFotos")
        self.gridLayout.addWidget(self.btnSubstituirFotos, 5, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnInserirModelo = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInserirModelo.sizePolicy().hasHeightForWidth())
        self.btnInserirModelo.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icones/word.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInserirModelo.setIcon(icon5)
        self.btnInserirModelo.setIconSize(QtCore.QSize(25, 25))
        self.btnInserirModelo.setObjectName("btnInserirModelo")
        self.verticalLayout.addWidget(self.btnInserirModelo)
        self.gridLayout.addLayout(self.verticalLayout, 6, 0, 1, 1)
        self.btnSubstituirSelecao = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSubstituirSelecao.sizePolicy().hasHeightForWidth())
        self.btnSubstituirSelecao.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icones/replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSubstituirSelecao.setIcon(icon6)
        self.btnSubstituirSelecao.setIconSize(QtCore.QSize(25, 25))
        self.btnSubstituirSelecao.setObjectName("btnSubstituirSelecao")
        self.gridLayout.addWidget(self.btnSubstituirSelecao, 1, 0, 1, 1)
        self.btnPesquisarFrase = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPesquisarFrase.sizePolicy().hasHeightForWidth())
        self.btnPesquisarFrase.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icones/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPesquisarFrase.setIcon(icon7)
        self.btnPesquisarFrase.setIconSize(QtCore.QSize(25, 25))
        self.btnPesquisarFrase.setObjectName("btnPesquisarFrase")
        self.gridLayout.addWidget(self.btnPesquisarFrase, 5, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnInserirModelos = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInserirModelos.sizePolicy().hasHeightForWidth())
        self.btnInserirModelos.setSizePolicy(sizePolicy)
        self.btnInserirModelos.setIcon(icon5)
        self.btnInserirModelos.setIconSize(QtCore.QSize(25, 25))
        self.btnInserirModelos.setObjectName("btnInserirModelos")
        self.verticalLayout_3.addWidget(self.btnInserirModelos)
        self.gridLayout.addLayout(self.verticalLayout_3, 6, 1, 1, 1)
        self.btnInserirQuadro = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInserirQuadro.sizePolicy().hasHeightForWidth())
        self.btnInserirQuadro.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icones/quadro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInserirQuadro.setIcon(icon8)
        self.btnInserirQuadro.setIconSize(QtCore.QSize(25, 25))
        self.btnInserirQuadro.setObjectName("btnInserirQuadro")
        self.gridLayout.addWidget(self.btnInserirQuadro, 1, 2, 1, 1)
        self.btnInserirFiguras = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInserirFiguras.sizePolicy().hasHeightForWidth())
        self.btnInserirFiguras.setSizePolicy(sizePolicy)
        self.btnInserirFiguras.setIcon(icon1)
        self.btnInserirFiguras.setIconSize(QtCore.QSize(25, 25))
        self.btnInserirFiguras.setObjectName("btnInserirFiguras")
        self.gridLayout.addWidget(self.btnInserirFiguras, 3, 1, 1, 1)
        self.btnAdicionarFrase = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdicionarFrase.sizePolicy().hasHeightForWidth())
        self.btnAdicionarFrase.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icones/addword.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdicionarFrase.setIcon(icon9)
        self.btnAdicionarFrase.setIconSize(QtCore.QSize(25, 25))
        self.btnAdicionarFrase.setObjectName("btnAdicionarFrase")
        self.gridLayout.addWidget(self.btnAdicionarFrase, 6, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edtDimensoesTabela = QtWidgets.QLineEdit(self.centralwidget)
        self.edtDimensoesTabela.setObjectName("edtDimensoesTabela")
        self.horizontalLayout.addWidget(self.edtDimensoesTabela)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.btnInserirTabela = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInserirTabela.sizePolicy().hasHeightForWidth())
        self.btnInserirTabela.setSizePolicy(sizePolicy)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icones/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInserirTabela.setIcon(icon10)
        self.btnInserirTabela.setIconSize(QtCore.QSize(25, 25))
        self.btnInserirTabela.setObjectName("btnInserirTabela")
        self.verticalLayout_4.addWidget(self.btnInserirTabela)
        self.gridLayout.addLayout(self.verticalLayout_4, 3, 2, 1, 1)
        self.btnOutrasAcoes = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutrasAcoes.sizePolicy().hasHeightForWidth())
        self.btnOutrasAcoes.setSizePolicy(sizePolicy)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icones/action.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOutrasAcoes.setIcon(icon11)
        self.btnOutrasAcoes.setIconSize(QtCore.QSize(25, 25))
        self.btnOutrasAcoes.setObjectName("btnOutrasAcoes")
        self.gridLayout.addWidget(self.btnOutrasAcoes, 7, 0, 1, 1)
        self.btnAdicionarFraseRemota = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdicionarFraseRemota.sizePolicy().hasHeightForWidth())
        self.btnAdicionarFraseRemota.setSizePolicy(sizePolicy)
        self.btnAdicionarFraseRemota.setIcon(icon9)
        self.btnAdicionarFraseRemota.setIconSize(QtCore.QSize(25, 25))
        self.btnAdicionarFraseRemota.setObjectName("btnAdicionarFraseRemota")
        self.gridLayout.addWidget(self.btnAdicionarFraseRemota, 7, 2, 1, 1)
        self.btnLaudoRapido = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLaudoRapido.sizePolicy().hasHeightForWidth())
        self.btnLaudoRapido.setSizePolicy(sizePolicy)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icones/notebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLaudoRapido.setIcon(icon12)
        self.btnLaudoRapido.setIconSize(QtCore.QSize(25, 25))
        self.btnLaudoRapido.setObjectName("btnLaudoRapido")
        self.gridLayout.addWidget(self.btnLaudoRapido, 7, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 666, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Word Helper"))
        self.btnInserirFigurasLegenda.setText(_translate("MainWindow", "Inserir figuras (com legenda)"))
        self.btnInserirFotos.setText(_translate("MainWindow", "Inserir fotos"))
        self.btnSubstituirTudo.setText(_translate("MainWindow", "Substituir tudo"))
        self.btnSubstituirFotos.setText(_translate("MainWindow", "Substituir fotos"))
        self.btnInserirModelo.setText(_translate("MainWindow", "Inserir modelo (com substituição)"))
        self.btnSubstituirSelecao.setText(_translate("MainWindow", "Substituir seleção"))
        self.btnPesquisarFrase.setText(_translate("MainWindow", "Pesquisar frase"))
        self.btnInserirModelos.setText(_translate("MainWindow", "Inserir modelos"))
        self.btnInserirQuadro.setText(_translate("MainWindow", "Inserir Quadro"))
        self.btnInserirFiguras.setText(_translate("MainWindow", "Inserir figuras"))
        self.btnAdicionarFrase.setText(_translate("MainWindow", "Adicionar frase"))
        self.label.setText(_translate("MainWindow", "Dimensões"))
        self.edtDimensoesTabela.setText(_translate("MainWindow", "1,1"))
        self.btnInserirTabela.setText(_translate("MainWindow", "Inserir Tabela"))
        self.btnOutrasAcoes.setText(_translate("MainWindow", "Outras ações"))
        self.btnAdicionarFraseRemota.setText(_translate("MainWindow", "Adicionar frase remota"))
        self.btnLaudoRapido.setText(_translate("MainWindow", "Laudo rápido"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

