# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'case_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CaseDialog(object):
    def setupUi(self, CaseDialog):
        CaseDialog.setObjectName("CaseDialog")
        CaseDialog.resize(401, 109)
        self.verticalLayout = QtWidgets.QVBoxLayout(CaseDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(CaseDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.led_name = QtWidgets.QLineEdit(CaseDialog)
        self.led_name.setObjectName("led_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.led_name)
        self.typeLabel = QtWidgets.QLabel(CaseDialog)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.cbx_role = QtWidgets.QComboBox(CaseDialog)
        self.cbx_role.setObjectName("cbx_role")
        self.cbx_role.addItem("")
        self.cbx_role.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbx_role)
        self.verticalLayout.addLayout(self.formLayout)
        self.bbx_box = QtWidgets.QDialogButtonBox(CaseDialog)
        self.bbx_box.setOrientation(QtCore.Qt.Horizontal)
        self.bbx_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbx_box.setCenterButtons(False)
        self.bbx_box.setObjectName("bbx_box")
        self.verticalLayout.addWidget(self.bbx_box)

        self.retranslateUi(CaseDialog)
        QtCore.QMetaObject.connectSlotsByName(CaseDialog)

    def retranslateUi(self, CaseDialog):
        _translate = QtCore.QCoreApplication.translate
        CaseDialog.setWindowTitle(_translate("CaseDialog", "Case Dialog"))
        self.nameLabel.setText(_translate("CaseDialog", "Name"))
        self.typeLabel.setText(_translate("CaseDialog", "Role"))
        self.cbx_role.setItemText(0, _translate("CaseDialog", "temp"))
        self.cbx_role.setItemText(1, _translate("CaseDialog", "final"))
