# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disk_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiskDialog(object):
    def setupUi(self, DiskDialog):
        DiskDialog.setObjectName("DiskDialog")
        DiskDialog.resize(401, 109)
        self.verticalLayout = QtWidgets.QVBoxLayout(DiskDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(DiskDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.led_name = QtWidgets.QLineEdit(DiskDialog)
        self.led_name.setObjectName("led_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.led_name)
        self.typeLabel = QtWidgets.QLabel(DiskDialog)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.cbx_subtype = QtWidgets.QComboBox(DiskDialog)
        self.cbx_subtype.setObjectName("cbx_subtype")
        self.cbx_subtype.addItem("")
        self.cbx_subtype.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbx_subtype)
        self.verticalLayout.addLayout(self.formLayout)
        self.bbx_box = QtWidgets.QDialogButtonBox(DiskDialog)
        self.bbx_box.setOrientation(QtCore.Qt.Horizontal)
        self.bbx_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbx_box.setCenterButtons(False)
        self.bbx_box.setObjectName("bbx_box")
        self.verticalLayout.addWidget(self.bbx_box)

        self.retranslateUi(DiskDialog)
        QtCore.QMetaObject.connectSlotsByName(DiskDialog)

    def retranslateUi(self, DiskDialog):
        _translate = QtCore.QCoreApplication.translate
        DiskDialog.setWindowTitle(_translate("DiskDialog", "Disk Dialog"))
        self.nameLabel.setText(_translate("DiskDialog", "Name"))
        self.typeLabel.setText(_translate("DiskDialog", "Subtype"))
        self.cbx_subtype.setItemText(0, _translate("DiskDialog", "interno"))
        self.cbx_subtype.setItemText(1, _translate("DiskDialog", "externo"))
