# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spb_depth = QtWidgets.QSpinBox(self.centralwidget)
        self.spb_depth.setMinimum(1)
        self.spb_depth.setProperty("value", 5)
        self.spb_depth.setObjectName("spb_depth")
        self.horizontalLayout.addWidget(self.spb_depth)
        self.led_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.led_folder.setReadOnly(True)
        self.led_folder.setObjectName("led_folder")
        self.horizontalLayout.addWidget(self.led_folder)
        self.btn_choose_folder = QtWidgets.QToolButton(self.centralwidget)
        self.btn_choose_folder.setObjectName("btn_choose_folder")
        self.horizontalLayout.addWidget(self.btn_choose_folder)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tbv_markers = QtWidgets.QTableView(self.centralwidget)
        self.tbv_markers.setAlternatingRowColors(True)
        self.tbv_markers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_markers.setObjectName("tbv_markers")
        self.tbv_markers.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tbv_markers)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_scan_all = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scan_all.setObjectName("btn_scan_all")
        self.horizontalLayout_2.addWidget(self.btn_scan_all)
        self.btn_open_folder = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_folder.setObjectName("btn_open_folder")
        self.horizontalLayout_2.addWidget(self.btn_open_folder)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sinf Mark"))
        self.label.setText(_translate("MainWindow", "Depth"))
        self.btn_choose_folder.setText(_translate("MainWindow", "..."))
        self.btn_scan_all.setText(_translate("MainWindow", "Scan all"))
        self.btn_open_folder.setText(_translate("MainWindow", "Open folder"))
