# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 408)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.led_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.led_folder.setReadOnly(True)
        self.led_folder.setObjectName("led_folder")
        self.horizontalLayout.addWidget(self.led_folder)
        self.btn_choose_folder = QtWidgets.QToolButton(self.centralwidget)
        self.btn_choose_folder.setObjectName("btn_choose_folder")
        self.horizontalLayout.addWidget(self.btn_choose_folder)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lsw_main = QtWidgets.QListWidget(self.centralwidget)
        self.lsw_main.setObjectName("lsw_main")
        self.verticalLayout.addWidget(self.lsw_main)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_scan_drives = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scan_drives.setObjectName("btn_scan_drives")
        self.horizontalLayout_2.addWidget(self.btn_scan_drives)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sinf Mark"))
        self.btn_choose_folder.setText(_translate("MainWindow", "..."))
        self.btn_scan_drives.setText(_translate("MainWindow", "Ver drives"))
        self.pushButton_2.setText(_translate("MainWindow", "Ver discos"))
